version: "3.7"

# startDB's script
# start service

services:
  #AUTH
  auth:
    container_name: auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./auth-service:/auth-service
    ports:
      - 3000:3000
    environment:
      USER: Dragan
    working_dir: /auth-service
    command: sh -c "cargo install cargo-watch && cargo-watch -x run"

  #MONGO
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: CHAT-SERVICE
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro

  # POSTGRES
  postgres:
    container_name: postgres
    restart: always
    build: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: ROOM-SERVICE
