version: "3.7"

# services for auth mongodb
# services for rooms postgres

services:
  #MONGO
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: CHAT-SERVICE
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
  # POSTGRES
  postgres:
    restart: always
    build: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: ROOM-SERVICE
