version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    environment:
      - REACT_APP_CLIENT_URL=http://localhost:3050
      - REACT_APP_SERVER_URL=http://localhost:5000/api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - NODE_ENV=development
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=pgpassword
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET='zawarudo'
  redis-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./redis-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /usr/app/node_modules
      - ./redis-server:/usr/app