// <auto-generated />
using System;
using InventoryService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InventoryService.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20211029213049_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InventoryService.Models.Trinket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("UserInventoryId");

                    b.HasKey("Id");

                    b.HasIndex("UserInventoryId");

                    b.ToTable("Trinket");
                });

            modelBuilder.Entity("InventoryService.Models.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Exp");

                    b.Property<int>("NegativeRating");

                    b.Property<int>("PositiveRating");

                    b.HasKey("Id");

                    b.ToTable("UserInventories");
                });

            modelBuilder.Entity("InventoryService.Models.Trinket", b =>
                {
                    b.HasOne("InventoryService.Models.UserInventory")
                        .WithMany("Trinkets")
                        .HasForeignKey("UserInventoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
