// <auto-generated />
using System;
using InventoryService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryService.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryService.Models.Trinket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("UserInventoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserInventoryId");

                    b.ToTable("Trinket");
                });

            modelBuilder.Entity("InventoryService.Models.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Exp")
                        .HasColumnType("bigint");

                    b.Property<int>("NegativeRating")
                        .HasColumnType("integer");

                    b.Property<int>("PositiveRating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserInventories");
                });

            modelBuilder.Entity("InventoryService.Models.Trinket", b =>
                {
                    b.HasOne("InventoryService.Models.UserInventory", null)
                        .WithMany("Trinkets")
                        .HasForeignKey("UserInventoryId");
                });

            modelBuilder.Entity("InventoryService.Models.UserInventory", b =>
                {
                    b.Navigation("Trinkets");
                });
#pragma warning restore 612, 618
        }
    }
}
